from odoo import models, fields, api
import random

class config(models.TransientModel):
    _inherit = 'res.config.settings'
    players = fields.Char(string='players',
                             config_parameter="roma.players")


    def reset_republic(self):
        print("reset",self)
        cities = [
            "Roman city",
            "Aballava",
            "Aballo (Aballum)",
            "Abdera",
            "Abritus (Abrittus)",
            "Abudiacum",
            "Abula",
            "Abusina",
            "Acci",
            "Acinipo",
            "Acrae",
            "Ad Anisum",
            "Ad Flexum",
            "Ad Iuvense",
            "Ad Mauros",
            "Ad Mediam",
            "Ad Novas",
            "Adana",
            "Ader",
            "Adraa",
            "Adramyttium",
            "Ad Statuas",
            "Ad Statuas",
            "Aelia Capitolina",
            "Aelium Cetium",
            "Aeminium",
            "Aenus",
            "Aequinoctium",
            "Aesica",
            "Agathe",
            "Agedincum",
            "Agrigentum",
            "Aguntum",
            "Ala Nova",
            "Altinum",
            "Albanum",
            "Almus",
            "Amida",
            "Ambracia",
            "Acyra",
            "Anderida",
            "Anhialo (Anchialus)",
            "Anicium",
            "Anio",
            "Antioch",
            "Antipolis",
            "Antium",
            "Apamea",
            "Apamea (Celaenae)",
            "Aphrodisias",
            "Apollonia",
            "Apollonia Pontica",
            "Apulum",
            "Aquae Cutiliae",
            "Aquae Helveticae",
            "Aquae Sextiae",
            "Aquae Sulis",
            "Aqua Viva",
            "Aquitania",
            "Aquis Voconis",
            "Aquileia",
            "Aquincum",
            "Aquisgranium",
            "Arausio",
            "Arbeia",
            "Arcadiopolis (Bergula)",
            "Arcidava",
            "Arelape",
            "Arelate",
            "Argentoratum",
            "Ariminium",
            "Armorica",
            "Arrabona",
            "Arsinoe",
            "Arverni",
            "Asisium",
            "Ascalon",
            "Asturica",
            "Athenae",
            "Atrans",
            "Atrebatum",
            "Augusta Emerita",
            "Augusta Praetoria",
            "Augusta Raurica",
            "Augusta Taurinorum",
            "Augusta Trajana",
            "Augusta Trebecorum",
            "Augusta Trevirorum",
            "Augusta Vindelicorum",
            "Augustianis",
            "Augustobona",
            "Augustodunum",
            "Augustonementum",
            "Aurelia",
            "Aurelia Aquensi",
            "Autricum",
            "Avennio",
            "Aventicum",
            "Baeterrae",
            "Baeloe",
            "Baetulo",
            "Baiae",
            "Barcino",
            "Barium",
            "Basti",
            "Batavis",
            "Bedriacum",
            "Belgica",
            "Belginum",
            "Beneventum",
            "Bergomum",
            "Bergula",
            "Beroe Augusta Trajana",
            "Berytus",
            "Berzobis",
            "Bethar",
            "Bilbilis (Bilbilis Italica)",
            "Bisanthe",
            "Blariacum",
            "Bona",
            "Bononia",
            "Bononia",
            "Bononia",
            "Bononia Malata",
            "Bostra",
            "Bracara Augusta",
            "Bremetennacum Veteranorum",
            "Brigantium",
            "Brigantium",
            "Brigetio",
            "Britannia",
            "Brivas",
            "Brixellum",
            "Brundisium",
            "Budalia",
            "Burdigala",
            "Burrium",
            "Byblus",
            "Caenophrurium",
            "Caesaraugusta",
            "Caesarea",
            "Caesarea Maritima",
            "Caesarea Mazaca",
            "Caesarodunum",
            "Caesena",
            "Calagurris (Calagurris Iulia Nasica)",
            "Calagurris Iulia Nasica (Calagurris)",
            "Calceus Herculis",
            "Caledonia",
            "Callatis",
            "Calleva Atrebatum",
            "Cambria",
            "Campi Catalaunii",
            "Campona",
            "Camulodunum",
            "Canatha",
            "Cannae",
            "Cantabrigia",
            "Caprae",
            "Caprera",
            "Capsa",
            "Carcaso",
            "Carmo (Carmona)",
            "Carmona (Carmo)",
            "Carnotum (Autricum)",
            "Carnuntum",
            "Carrhae",
            "Carteia",
            "Cartennae",
            "Carthago",
            "Carthago Nova",
            "Cascantum",
            "Castellum apud Confluentes",
            "Castellum Flevum",
            "Castra ad Herculem",
            "Castra Batavorum (Batavis)",
            "Castra Martis",
            "Castra Regina",
            "Castrum Octavianum",
            "Castulo",
            "Cataractonium",
            "Cauca",
            "Celaenae, Apamea",
            "Celeia",
            "Celsa (Colonia Victrix Iulia Lepida)",
            "Cenabum Aureliani (Aurelia)",
            "Cenebelum",
            "Chalcedon",
            "Chrysopolis",
            "Chullu",
            "Cibalae",
            "Cillium",
            "Circesium",
            "Cilurnum",
            "Cirpi",
            "Cirta",
            "Claudiopolis (Napoca)",
            "Clunia",
            "Clusium",
            "Colonia Agrippina",
            "Colonia Agrippinensium",
            "Colonia Augusta Emerita (Emerita)",
            "Colonia Patricia, Corduba",
            "Colonia Ulpia Traiana (Vetera)",
            "Colonia Victrix Iulia Lepida",
            "Comagena",
            "Complutum",
            "Comum",
            "Concordia Sagittaria",
            "Condate Redones",
            "Conimbriga",
            "Constantia",
            "Constantia",
            "Constantinopolis (Byzantium)",
            "Corduba",
            "Coria",
            "Coriallum",
            "Corinium",
            "Coriovallum",
            "Corisopitum",
            "Coristopitum, Coria",
            "Cortoriacum",
            "Corvinium",
            "Cuicul",
            "Cularo",
            "Cunetio",
            "Curia",
            "Cyrene",
            "Danaster (Tyras)",
            "Danum",
            "Dertona",
            "Dertosa",
            "Derventio",
            "Deva",
            "Dianinum",
            "Dierna",
            "Diocletianopolis",
            "Dionysopolis",
            "Drobeta",
            "Dubris",
            "Dunum",
            "Duranius",
            "Durnovaria",
            "Durocorotum",
            "Durostorum",
            "Durovernum Cantiacorum",
            "Dyrrachium, Epidamnus",
            "Ebrus",
            "Eburacum",
            "Eburodunum",
            "Egara",
            "Emerita",
            "Emesa",
            "Emporiae",
            "Epidamnus",
            "Faesulae",
            "Favianis",
            "Flavia Solva",
            "Florentia",
            "Forum Claudii Vallensium",
            "Forum Hadriani",
            "Gades",
            "Gandava",
            "Gariannonum",
            "Garumna",
            "Geneva",
            "Gerasa",
            "Gerulata",
            "Gesoriacum",
            "Glannaventa",
            "Glevum",
            "Gorsium (Herculea)",
            "Graccurris",
            "Gratianopolis (Cularo)",
            "Hadrianopolis",
            "Haga-Comitis",
            "Heliopolis",
            "Heraclea (Perinthus)",
            "Heraclea Lyncestis",
            "Hibernia",
            "Hierosolyma (Aelia Capitolina)",
            "Hippo Regius",
            "Hispalis",
            "Histria",
            "Iaurinum",
            "Iberia",
            "Ilerda",
            "Illici",
            "Intercisa",
            "Ioviacum",
            "Isara",
            "Isca Dumnoniorum",
            "Isca",
            "Istropolis",
            "Istrus",
            "Isurium",
            "Italica",
            "Iulia Concordia",
            "Iulia Traducta",
            "Labacum (Aemona)",
            "Lascuta",
            "Latopolis",
            "Lauriacum",
            "Lavatrae",
            "Lederata",
            "Legio",
            "Lentia",
            "Letocetum",
            "Leucarum",
            "Liburnum",
            "Liger",
            "Lihnidos",
            "Limonum",
            "Lincium",
            "Lindinis",
            "Lindum",
            "Londinium",
            "Lucentum",
            "Lucus Augusti",
            "Lugdunum",
            "Lugdunum Batavorum",
            "Luguvalium",
            "Lusitania",
            "Lussonium",
            "Lutetia Parisiorum",
            "Madauros",
            "Magador",
            "Malaca",
            "Malata Bonenia",
            "Mazaca (Caesarea Mazaca)",
            "Mamucium",
            "Marcianopolis",
            "Massilia",
            "Matrica",
            "Mediolanum",
            "Mediolanum Aulercorum",
            "Mediolanum Santonum",
            "Melitene",
            "Melta",
            "Messambria",
            "Messana",
            "Metellinum",
            "Metis",
            "Misenum",
            "Moenum",
            "Mogentianae",
            "Moguntiacum",
            "Mons Bellona",
            "Montana",
            "Moridunum",
            "Municipium Augusta Bilbilis",
            "Mursa",
            "Mutina",
            "Naissus",
            "Napoca",
            "Narbo",
            "Neapolis",
            "Nemausus",
            "Nervia Glevensium",
            "Neviodunum",
            "Nidum",
            "Norba",
            "Novae",
            "Noviomagus",
            "Noviomagus",
            "Noviomagus Batavodurum (Ulpia Novomagus)",
            "Novioritum",
            "Novodunum",
            "Numantia",
            "Obulco",
            "Octodurus",
            "Odessus",
            "Oea",
            "Oenipontum",
            "Olicana",
            "Olisipo",
            "Onuba",
            "Opitergium",
            "Osca (Urbs Victrix Osca)",
            "Osset",
            "Ossonoba",
            "Palmyra",
            "Parentium",
            "Patavium",
            "Pautalia",
            "Pax Iulia",
            "Perinthus (Heraclea)",
            "Perusia",
            "Philadelphia",
            "Philippopolis, Trimontium",
            "Pisae",
            "Placentia",
            "Podium Aniciense (Anicium)",
            "Poetovio",
            "Pola",
            "Pompaelo",
            "Pompeii",
            "Pons Aelius",
            "Portus",
            "Portus Adurni",
            "Portus Cale",
            "Portus Itius (Gesoriacum)",
            "Posonium (Istropolis)",
            "Potaissa",
            "Praetorium Agrippinae",
            "Praetorium Latobicorum",
            "Ptolemais",
            "Pumbedita",
            "Puteoli",
            "Quinque-Ecclesiis",
            "Ratea Colitanorum",
            "Raetinium",
            "Raphae",
            "Ratae Coritanorum",
            "Ratiara",
            "Ravenna",
            "Regulbium",
            "Resapha",
            "Rhaedestus, Bisanthe",
            "Rhegium",
            "Rhenus",
            "Rhodanos",
            "Rigomagus",
            "Risinium",
            "Roma",
            "Rotomagus",
            "Rusaddir",
            "Rusicade",
            "Rutupiae",
            "Sabratha",
            "Saguntum",
            "Saldae",
            "Salmantica",
            "Salonae",
            "Salva",
            "Samarobriva (Ambiani)",
            "Sarmizegethusa (Colonia Ulpia Traiana)",
            "Savaria (Colonia Claudia Savaria)",
            "Scarbantia",
            "Scupi (Colonia Flavia Scup",
            "Sempronium (Sopronium)",
            "Senones (Agedincum)",
            "Serdica",
            "Sergiopolis (Resapha)",
            "Sexaginta Prista",
            "Sicca Veneria",
            "Simitthu",
            "Singidunum",
            "Sinope",
            "Sippar",
            "Sirmium",
            "Siscia",
            "Solva",
            "Sopianae",
            "Sorviodurum",
            "Sozopolis (Apollonia Pontica)",
            "Spalatum",
            "Stobi",
            "Storgozia",
            "Sucidava",
            "Sufetula",
            "Syene",
            "Syracusae",
            "Taparura",
            "Tarentum",
            "Tarraco",
            "Tarvisium",
            "Taurinum (Augusta Taurinorum)",
            "Tentyra",
            "Tergeste",
            "Thugga",
            "Thysdrus",
            "Ticinum",
            "Tigurum (Turicim)",
            "Tingi",
            "Toletum",
            "Tomis",
            "Traiectum ad Mosam",
            "Traiectum Eriditum",
            "Trapezus (Trebizond)",
            "Trebizond (Trapezus)",
            "Treviri (Augusta Treverorum)",
            "Tricciana",
            "Tridentum",
            "Trimontium",
            "Trimontium (Philippopolis)",
            "Tripolis",
            "Tropaeum Traiani",
            "Tupusuctu",
            "Turiaso (Turiaso Silbis)",
            "Turiaso Silbis",
            "Turicim (Tigurum)",
            "Turnacum Nerviorum",
            "Tyrus",
            "Ugernum",
            "Ulcisia Castra",
            "Ulpia Novomagus(Noviomagus Batavodurum)",
            "Urbs Victrix Osca (Osca)",
            "Utinum",
            "Valcum",
            "Valentia",
            "Valentia Edetanorum",
            "Varadinum",
            "Veldidena",
            "Venetiae",
            "Venta Belgarum",
            "Venta Silurum",
            "Vernementum",
            "Verulamium",
            "Vesunna",
            "Vetera (Colonia Ulpia Trajana)",
            "Vicentia",
            "Vicus Belginum (Belginum)",
            "Vienna",
            "Vienna (Vindobona)",
            "Viminiacum",
            "Vindobona (Vienna)",
            "Vindomora",
            "Vindonissa",
            "Vinovia (Vinovium)",
            "Vinovium (Vinovia)",
            "Vitudurum",
            "Viroconium Cornoviorum",
            "Vizeliacum",
            "Xanthus",
            "Zama Regia",
            "Zela",
            "Zeugma"
        ]
        self.env['roma.city'].search([]).unlink()
        for city in cities:
            self.env['roma.city'].create({
                "name": city,
                "level": "1",
                "health": random.randint(0,100),
                "loyalty": random.randint(0,100),
                "gods":0,
                "metal":random.randint(0,100),
                "gold":random.randint(0,100),
                "food":random.randint(0,100)
            })
